# Generated by Django 3.2.12 on 2022-07-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_buku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buku',
        ),
    ]
