# Generated by Django 3.2.12 on 2022-07-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_products_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.CharField(max_length=100),
        ),
    ]
