# Generated by Django 3.2.14 on 2022-07-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_alter_products_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stok',
            field=models.FloatField(default=0),
        ),
    ]
