# Generated by Django 3.2.14 on 2022-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_products_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
