# Generated by Django 3.2.14 on 2022-07-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_alter_products_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
