# Generated by Django 3.2.14 on 2022-07-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_salesitems_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='stok',
        ),
        migrations.AddField(
            model_name='sales',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
