# Generated by Django 3.2.14 on 2022-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_auto_20220731_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stok',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='stok',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
